<?php
// Generated by https://github.com/bramp/protoc-gen-php// Please include protocolbuffers before this file, for example:
//   require('protocolbuffers.inc.php');
//   require('POGOProtos/Data/Gym/GymMembership.php');

namespace POGOProtos\Data\Gym {

  use Protobuf;
  use ProtobufEnum;
  use ProtobufIO;
  use ProtobufMessage;


  // message POGOProtos.Data.Gym.GymMembership
  final class GymMembership extends ProtobufMessage {

    private $_unknown;
    private $pokemonData = null; // optional .POGOProtos.Data.PokemonData pokemon_data = 1
    private $trainerPublicProfile = null; // optional .POGOProtos.Data.Player.PlayerPublicProfile trainer_public_profile = 2

    public function __construct($in = null, &$limit = PHP_INT_MAX) {
      parent::__construct($in, $limit);
    }

    public function read($fp, &$limit = PHP_INT_MAX) {
      $fp = ProtobufIO::toStream($fp, $limit);
      while(!feof($fp) && $limit > 0) {
        $tag = Protobuf::read_varint($fp, $limit);
        if ($tag === false) break;
        $wire  = $tag & 0x07;
        $field = $tag >> 3;
        switch($field) {
          case 1: // optional .POGOProtos.Data.PokemonData pokemon_data = 1
            if($wire !== 2) {
              throw new \Exception("Incorrect wire format for field $field, expected: 2 got: $wire");
            }
            $len = Protobuf::read_varint($fp, $limit);
            if ($len === false) throw new \Exception('Protobuf::read_varint returned false');
            $limit -= $len;
            $this->pokemonData = new \POGOProtos\Data\PokemonData($fp, $len);
            if ($len !== 0) throw new \Exception('new \POGOProtos\Data\PokemonData did not read the full length');

            break;
          case 2: // optional .POGOProtos.Data.Player.PlayerPublicProfile trainer_public_profile = 2
            if($wire !== 2) {
              throw new \Exception("Incorrect wire format for field $field, expected: 2 got: $wire");
            }
            $len = Protobuf::read_varint($fp, $limit);
            if ($len === false) throw new \Exception('Protobuf::read_varint returned false');
            $limit -= $len;
            $this->trainerPublicProfile = new \POGOProtos\Data\Player\PlayerPublicProfile($fp, $len);
            if ($len !== 0) throw new \Exception('new \POGOProtos\Data\Player\PlayerPublicProfile did not read the full length');

            break;
          default:
            $limit -= Protobuf::skip_field($fp, $wire);
        }
      }
    }

    public function write($fp) {
      if ($this->pokemonData !== null) {
        fwrite($fp, "\x0a", 1);
        Protobuf::write_varint($fp, $this->pokemonData->size());
        $this->pokemonData->write($fp);
      }
      if ($this->trainerPublicProfile !== null) {
        fwrite($fp, "\x12", 1);
        Protobuf::write_varint($fp, $this->trainerPublicProfile->size());
        $this->trainerPublicProfile->write($fp);
      }
    }

    public function size() {
      $size = 0;
      if ($this->pokemonData !== null) {
        $l = $this->pokemonData->size();
        $size += 1 + Protobuf::size_varint($l) + $l;
      }
      if ($this->trainerPublicProfile !== null) {
        $l = $this->trainerPublicProfile->size();
        $size += 1 + Protobuf::size_varint($l) + $l;
      }
      return $size;
    }

    public function clearPokemonData() { $this->pokemonData = null; }
    public function getPokemonData() { return $this->pokemonData;}
    public function setPokemonData(\POGOProtos\Data\PokemonData $value) { $this->pokemonData = $value; }

    public function clearTrainerPublicProfile() { $this->trainerPublicProfile = null; }
    public function getTrainerPublicProfile() { return $this->trainerPublicProfile;}
    public function setTrainerPublicProfile(\POGOProtos\Data\Player\PlayerPublicProfile $value) { $this->trainerPublicProfile = $value; }

    public function __toString() {
      return ''
           . Protobuf::toString('pokemon_data', $this->pokemonData, null)
           . Protobuf::toString('trainer_public_profile', $this->trainerPublicProfile, null);
    }

    // @@protoc_insertion_point(class_scope:POGOProtos.Data.Gym.GymMembership)
  }

}