<?php
// Generated by https://github.com/bramp/protoc-gen-php// Please include protocolbuffers before this file, for example:
//   require('protocolbuffers.inc.php');
//   require('POGOProtos/Data/DownloadUrlEntry.php');

namespace POGOProtos\Data {

  use Protobuf;
  use ProtobufEnum;
  use ProtobufIO;
  use ProtobufMessage;

  // message POGOProtos.Data.DownloadUrlEntry
  final class DownloadUrlEntry extends ProtobufMessage {

    private $_unknown;
    private $assetId = ""; // optional string asset_id = 1
    private $url = ""; // optional string url = 2
    private $size = 0; // optional int32 size = 3
    private $checksum = 0; // optional uint32 checksum = 4

    public function __construct($in = null, &$limit = PHP_INT_MAX) {
      parent::__construct($in, $limit);
    }

    public function read($fp, &$limit = PHP_INT_MAX) {
      $fp = ProtobufIO::toStream($fp, $limit);
      while(!feof($fp) && $limit > 0) {
        $tag = Protobuf::read_varint($fp, $limit);
        if ($tag === false) break;
        $wire  = $tag & 0x07;
        $field = $tag >> 3;
        switch($field) {
          case 1: // optional string asset_id = 1
            if($wire !== 2) {
              throw new \Exception("Incorrect wire format for field $field, expected: 2 got: $wire");
            }
            $len = Protobuf::read_varint($fp, $limit);
            if ($len === false) throw new \Exception('Protobuf::read_varint returned false');
            $tmp = Protobuf::read_bytes($fp, $len, $limit);
            if ($tmp === false) throw new \Exception("read_bytes($len) returned false");
            $this->assetId = $tmp;

            break;
          case 2: // optional string url = 2
            if($wire !== 2) {
              throw new \Exception("Incorrect wire format for field $field, expected: 2 got: $wire");
            }
            $len = Protobuf::read_varint($fp, $limit);
            if ($len === false) throw new \Exception('Protobuf::read_varint returned false');
            $tmp = Protobuf::read_bytes($fp, $len, $limit);
            if ($tmp === false) throw new \Exception("read_bytes($len) returned false");
            $this->url = $tmp;

            break;
          case 3: // optional int32 size = 3
            if($wire !== 0) {
              throw new \Exception("Incorrect wire format for field $field, expected: 0 got: $wire");
            }
            $tmp = Protobuf::read_signed_varint($fp, $limit);
            if ($tmp === false) throw new \Exception('Protobuf::read_varint returned false');
            if ($tmp < Protobuf::MIN_INT32 || $tmp > Protobuf::MAX_INT32) throw new \Exception('int32 out of range');$this->size = $tmp;

            break;
          case 4: // optional uint32 checksum = 4
            if($wire !== 0) {
              throw new \Exception("Incorrect wire format for field $field, expected: 0 got: $wire");
            }
            $tmp = Protobuf::read_varint($fp, $limit);
            if ($tmp === false) throw new \Exception('Protobuf::read_varint returned false');
            if ($tmp < Protobuf::MIN_UINT32 || $tmp > Protobuf::MAX_UINT32) throw new \Exception('uint32 out of range');$this->checksum = $tmp;

            break;
          default:
            $limit -= Protobuf::skip_field($fp, $wire);
        }
      }
    }

    public function write($fp) {
      if ($this->assetId !== "") {
        fwrite($fp, "\x0a", 1);
        Protobuf::write_varint($fp, strlen($this->assetId));
        fwrite($fp, $this->assetId);
      }
      if ($this->url !== "") {
        fwrite($fp, "\x12", 1);
        Protobuf::write_varint($fp, strlen($this->url));
        fwrite($fp, $this->url);
      }
      if ($this->size !== 0) {
        fwrite($fp, "\x18", 1);
        Protobuf::write_varint($fp, $this->size);
      }
      if ($this->checksum !== 0) {
        fwrite($fp, " ", 1);
        Protobuf::write_varint($fp, $this->checksum);
      }
    }

    public function size() {
      $size = 0;
      if ($this->assetId !== "") {
        $l = strlen($this->assetId);
        $size += 1 + Protobuf::size_varint($l) + $l;
      }
      if ($this->url !== "") {
        $l = strlen($this->url);
        $size += 1 + Protobuf::size_varint($l) + $l;
      }
      if ($this->size !== 0) {
        $size += 1 + Protobuf::size_varint($this->size);
      }
      if ($this->checksum !== 0) {
        $size += 1 + Protobuf::size_varint($this->checksum);
      }
      return $size;
    }

    public function clearAssetId() { $this->assetId = ""; }
    public function getAssetId() { return $this->assetId;}
    public function setAssetId($value) { $this->assetId = $value; }

    public function clearUrl() { $this->url = ""; }
    public function getUrl() { return $this->url;}
    public function setUrl($value) { $this->url = $value; }

    public function clearSize() { $this->size = 0; }
    public function getSize() { return $this->size;}
    public function setSize($value) { $this->size = $value; }

    public function clearChecksum() { $this->checksum = 0; }
    public function getChecksum() { return $this->checksum;}
    public function setChecksum($value) { $this->checksum = $value; }

    public function __toString() {
      return ''
           . Protobuf::toString('asset_id', $this->assetId, "")
           . Protobuf::toString('url', $this->url, "")
           . Protobuf::toString('size', $this->size, 0)
           . Protobuf::toString('checksum', $this->checksum, 0);
    }

    // @@protoc_insertion_point(class_scope:POGOProtos.Data.DownloadUrlEntry)
  }

}