<?php
// Generated by https://github.com/bramp/protoc-gen-php// Please include protocolbuffers before this file, for example:
//   require('protocolbuffers.inc.php');
//   require('POGOProtos/Networking/Requests/Messages/MarkTutorialCompleteMessage.php');

namespace POGOProtos\Networking\Requests\Messages {

  use Protobuf;
  use ProtobufEnum;
  use ProtobufIO;
  use ProtobufMessage;


  // message POGOProtos.Networking.Requests.Messages.MarkTutorialCompleteMessage
  final class MarkTutorialCompleteMessage extends ProtobufMessage {

    private $_unknown;
    private $tutorialsCompleted = array(); // repeated .POGOProtos.Enums.TutorialState tutorials_completed = 1
    private $sendMarketingEmails = false; // optional bool send_marketing_emails = 2
    private $sendPushNotifications = false; // optional bool send_push_notifications = 3

    public function __construct($in = null, &$limit = PHP_INT_MAX) {
      parent::__construct($in, $limit);
    }

    public function read($fp, &$limit = PHP_INT_MAX) {
      $fp = ProtobufIO::toStream($fp, $limit);
      while(!feof($fp) && $limit > 0) {
        $tag = Protobuf::read_varint($fp, $limit);
        if ($tag === false) break;
        $wire  = $tag & 0x07;
        $field = $tag >> 3;
        switch($field) {
          case 1: // repeated .POGOProtos.Enums.TutorialState tutorials_completed = 1
            if($wire !== 2 && $wire !== 0) {
              throw new \Exception("Incorrect wire format for field $field, expected: 2 or 0 got: $wire");
            }
            if ($wire === 0) {
              $tmp = Protobuf::read_varint($fp, $limit);
              if ($tmp === false) throw new \Exception('Protobuf::read_varint returned false');
              $this->tutorialsCompleted[] = $tmp;
            } elseif ($wire === 2) {
              $len = Protobuf::read_varint($fp, $limit);
              while ($len > 0) {
                $tmp = Protobuf::read_varint($fp, $len);
                if ($tmp === false) throw new \Exception('Protobuf::read_varint returned false');
                $this->tutorialsCompleted[] = $tmp;
              }
            }

            break;
          case 2: // optional bool send_marketing_emails = 2
            if($wire !== 0) {
              throw new \Exception("Incorrect wire format for field $field, expected: 0 got: $wire");
            }
            $tmp = Protobuf::read_varint($fp, $limit);
            if ($tmp === false) throw new \Exception('Protobuf::read_varint returned false');
            $this->sendMarketingEmails = ($tmp > 0) ? true : false;

            break;
          case 3: // optional bool send_push_notifications = 3
            if($wire !== 0) {
              throw new \Exception("Incorrect wire format for field $field, expected: 0 got: $wire");
            }
            $tmp = Protobuf::read_varint($fp, $limit);
            if ($tmp === false) throw new \Exception('Protobuf::read_varint returned false');
            $this->sendPushNotifications = ($tmp > 0) ? true : false;

            break;
          default:
            $limit -= Protobuf::skip_field($fp, $wire);
        }
      }
    }

    public function write($fp) {
      foreach($this->tutorialsCompleted as $v) {
        fwrite($fp, "\x08", 1);
        Protobuf::write_varint($fp, $v);
      }
      if ($this->sendMarketingEmails !== false) {
        fwrite($fp, "\x10", 1);
        Protobuf::write_varint($fp, $this->sendMarketingEmails ? 1 : 0);
      }
      if ($this->sendPushNotifications !== false) {
        fwrite($fp, "\x18", 1);
        Protobuf::write_varint($fp, $this->sendPushNotifications ? 1 : 0);
      }
    }

    public function size() {
      $size = 0;
      foreach($this->tutorialsCompleted as $v) {
        $l = strlen($v);
        $size += 1 + Protobuf::size_varint($l) + $l;
      }
      if ($this->sendMarketingEmails !== false) {
        $size += 2;
      }
      if ($this->sendPushNotifications !== false) {
        $size += 2;
      }
      return $size;
    }

    public function clearTutorialsCompleted() { $this->tutorialsCompleted = array(); }
    public function getTutorialsCompletedCount() { return count($this->tutorialsCompleted); }
    public function getTutorialsCompleted($index) { return $this->tutorialsCompleted[$index]; }
    public function getTutorialsCompletedArray() { return $this->tutorialsCompleted; }
    public function setTutorialsCompleted($index, array $value) {$this->tutorialsCompleted[$index] = $value; }
    public function addTutorialsCompleted(array $value) { $this->tutorialsCompleted[] = $value; }
    public function addAllTutorialsCompleted(array $values) { foreach($values as $value) {$this->tutorialsCompleted[] = $value; }}

    public function clearSendMarketingEmails() { $this->sendMarketingEmails = false; }
    public function getSendMarketingEmails() { return $this->sendMarketingEmails;}
    public function setSendMarketingEmails($value) { $this->sendMarketingEmails = $value; }

    public function clearSendPushNotifications() { $this->sendPushNotifications = false; }
    public function getSendPushNotifications() { return $this->sendPushNotifications;}
    public function setSendPushNotifications($value) { $this->sendPushNotifications = $value; }

    public function __toString() {
      return ''
           . Protobuf::toString('tutorials_completed', $this->tutorialsCompleted, TutorialState::LEGAL_SCREEN)
           . Protobuf::toString('send_marketing_emails', $this->sendMarketingEmails, false)
           . Protobuf::toString('send_push_notifications', $this->sendPushNotifications, false);
    }

    // @@protoc_insertion_point(class_scope:POGOProtos.Networking.Requests.Messages.MarkTutorialCompleteMessage)
  }

}