<?php
// Generated by https://github.com/bramp/protoc-gen-php// Please include protocolbuffers before this file, for example:
//   require('protocolbuffers.inc.php');
//   require('POGOProtos/Networking/Requests/Messages/SetAvatarMessage.php');

namespace POGOProtos\Networking\Requests\Messages {

  use Protobuf;
  use ProtobufEnum;
  use ProtobufIO;
  use ProtobufMessage;


  // message POGOProtos.Networking.Requests.Messages.SetAvatarMessage
  final class SetAvatarMessage extends ProtobufMessage {

    private $_unknown;
    private $playerAvatar = null; // optional .POGOProtos.Data.Player.PlayerAvatar player_avatar = 2

    public function __construct($in = null, &$limit = PHP_INT_MAX) {
      parent::__construct($in, $limit);
    }

    public function read($fp, &$limit = PHP_INT_MAX) {
      $fp = ProtobufIO::toStream($fp, $limit);
      while(!feof($fp) && $limit > 0) {
        $tag = Protobuf::read_varint($fp, $limit);
        if ($tag === false) break;
        $wire  = $tag & 0x07;
        $field = $tag >> 3;
        switch($field) {
          case 2: // optional .POGOProtos.Data.Player.PlayerAvatar player_avatar = 2
            if($wire !== 2) {
              throw new \Exception("Incorrect wire format for field $field, expected: 2 got: $wire");
            }
            $len = Protobuf::read_varint($fp, $limit);
            if ($len === false) throw new \Exception('Protobuf::read_varint returned false');
            $limit -= $len;
            $this->playerAvatar = new \POGOProtos\Data\Player\PlayerAvatar($fp, $len);
            if ($len !== 0) throw new \Exception('new \POGOProtos\Data\Player\PlayerAvatar did not read the full length');

            break;
          default:
            $limit -= Protobuf::skip_field($fp, $wire);
        }
      }
    }

    public function write($fp) {
      if ($this->playerAvatar !== null) {
        fwrite($fp, "\x12", 1);
        Protobuf::write_varint($fp, $this->playerAvatar->size());
        $this->playerAvatar->write($fp);
      }
    }

    public function size() {
      $size = 0;
      if ($this->playerAvatar !== null) {
        $l = $this->playerAvatar->size();
        $size += 1 + Protobuf::size_varint($l) + $l;
      }
      return $size;
    }

    public function clearPlayerAvatar() { $this->playerAvatar = null; }
    public function getPlayerAvatar() { return $this->playerAvatar;}
    public function setPlayerAvatar(\POGOProtos\Data\Player\PlayerAvatar $value) { $this->playerAvatar = $value; }

    public function __toString() {
      return ''
           . Protobuf::toString('player_avatar', $this->playerAvatar, null);
    }

    // @@protoc_insertion_point(class_scope:POGOProtos.Networking.Requests.Messages.SetAvatarMessage)
  }

}