<?php
// Generated by https://github.com/bramp/protoc-gen-php// Please include protocolbuffers before this file, for example:
//   require('protocolbuffers.inc.php');
//   require('POGOProtos/Map/Fort/FortRenderingType.php');

namespace POGOProtos\Map\Fort {

  use Protobuf;
  use ProtobufEnum;
  use ProtobufIO;
  use ProtobufMessage;

  // enum POGOProtos.Map.Fort.FortRenderingType
  abstract class FortRenderingType extends ProtobufEnum {
    const NONE = 0;
    const INTERNAL_TEST = 1;

    public static $_values = array(
      0 => "DEFAULT",
      1 => "INTERNAL_TEST",
    );

    public static function isValid($value) {
      return array_key_exists($value, self::$_values);
    }

    public static function toString($value) {
      checkArgument(is_int($value), 'value must be a integer');
      if (array_key_exists($value, self::$_values))
        return self::$_values[$value];
      return 'UNKNOWN';
    }
  }

}