<?php
// Generated by https://github.com/bramp/protoc-gen-php// Please include protocolbuffers before this file, for example:
//   require('protocolbuffers.inc.php');
//   require('POGOProtos/Map/Fort/FortLureInfo.php');

namespace POGOProtos\Map\Fort {

  use POGOProtos\Enums\PokemonId;
  use Protobuf;
  use ProtobufEnum;
  use ProtobufIO;
  use ProtobufMessage;


  // message POGOProtos.Map.Fort.FortLureInfo
  final class FortLureInfo extends ProtobufMessage {

    private $_unknown;
    private $fortId = ""; // optional string fort_id = 1
    private $encounterId = 0; // optional fixed64 encounter_id = 2
    private $activePokemonId = PokemonId::MISSINGNO; // optional .POGOProtos.Enums.PokemonId active_pokemon_id = 3
    private $lureExpiresTimestampMs = 0; // optional int64 lure_expires_timestamp_ms = 4

    public function __construct($in = null, &$limit = PHP_INT_MAX) {
      parent::__construct($in, $limit);
    }

    public function read($fp, &$limit = PHP_INT_MAX) {
      $fp = ProtobufIO::toStream($fp, $limit);
      while(!feof($fp) && $limit > 0) {
        $tag = Protobuf::read_varint($fp, $limit);
        if ($tag === false) break;
        $wire  = $tag & 0x07;
        $field = $tag >> 3;
        switch($field) {
          case 1: // optional string fort_id = 1
            if($wire !== 2) {
              throw new \Exception("Incorrect wire format for field $field, expected: 2 got: $wire");
            }
            $len = Protobuf::read_varint($fp, $limit);
            if ($len === false) throw new \Exception('Protobuf::read_varint returned false');
            $tmp = Protobuf::read_bytes($fp, $len, $limit);
            if ($tmp === false) throw new \Exception("read_bytes($len) returned false");
            $this->fortId = $tmp;

            break;
          case 2: // optional fixed64 encounter_id = 2
            if($wire !== 1) {
              throw new \Exception("Incorrect wire format for field $field, expected: 1 got: $wire");
            }
            $tmp = Protobuf::read_uint64($fp, $limit);
            if ($tmp === false) throw new \Exception('Protobuf::read_unint64 returned false');
            $this->encounterId = $tmp;

            break;
          case 3: // optional .POGOProtos.Enums.PokemonId active_pokemon_id = 3
            if($wire !== 0) {
              throw new \Exception("Incorrect wire format for field $field, expected: 0 got: $wire");
            }
            $tmp = Protobuf::read_varint($fp, $limit);
            if ($tmp === false) throw new \Exception('Protobuf::read_varint returned false');
            $this->activePokemonId = $tmp;

            break;
          case 4: // optional int64 lure_expires_timestamp_ms = 4
            if($wire !== 0) {
              throw new \Exception("Incorrect wire format for field $field, expected: 0 got: $wire");
            }
            $tmp = Protobuf::read_signed_varint($fp, $limit);
            if ($tmp === false) throw new \Exception('Protobuf::read_varint returned false');
            if ($tmp < Protobuf::MIN_INT64 || $tmp > Protobuf::MAX_INT64) throw new \Exception('int64 out of range');$this->lureExpiresTimestampMs = $tmp;

            break;
          default:
            $limit -= Protobuf::skip_field($fp, $wire);
        }
      }
    }

    public function write($fp) {
      if ($this->fortId !== "") {
        fwrite($fp, "\x0a", 1);
        Protobuf::write_varint($fp, strlen($this->fortId));
        fwrite($fp, $this->fortId);
      }
      if ($this->encounterId !== 0) {
        fwrite($fp, "\x11", 1);
        Protobuf::write_uint64($fp, $this->encounterId);
      }
      if ($this->activePokemonId !== PokemonId::MISSINGNO) {
        fwrite($fp, "\x18", 1);
        Protobuf::write_varint($fp, $this->activePokemonId);
      }
      if ($this->lureExpiresTimestampMs !== 0) {
        fwrite($fp, " ", 1);
        Protobuf::write_varint($fp, $this->lureExpiresTimestampMs);
      }
    }

    public function size() {
      $size = 0;
      if ($this->fortId !== "") {
        $l = strlen($this->fortId);
        $size += 1 + Protobuf::size_varint($l) + $l;
      }
      if ($this->encounterId !== 0) {
        $size += 9;
      }
      if ($this->activePokemonId !== PokemonId::MISSINGNO) {
        $size += 1 + Protobuf::size_varint($this->activePokemonId);
      }
      if ($this->lureExpiresTimestampMs !== 0) {
        $size += 1 + Protobuf::size_varint($this->lureExpiresTimestampMs);
      }
      return $size;
    }

    public function clearFortId() { $this->fortId = ""; }
    public function getFortId() { return $this->fortId;}
    public function setFortId($value) { $this->fortId = $value; }

    public function clearEncounterId() { $this->encounterId = 0; }
    public function getEncounterId() { return $this->encounterId;}
    public function setEncounterId($value) { $this->encounterId = $value; }

    public function clearActivePokemonId() { $this->activePokemonId = PokemonId::MISSINGNO; }
    public function getActivePokemonId() { return $this->activePokemonId;}
    public function setActivePokemonId($value) { $this->activePokemonId = $value; }

    public function clearLureExpiresTimestampMs() { $this->lureExpiresTimestampMs = 0; }
    public function getLureExpiresTimestampMs() { return $this->lureExpiresTimestampMs;}
    public function setLureExpiresTimestampMs($value) { $this->lureExpiresTimestampMs = $value; }

    public function __toString() {
      return ''
           . Protobuf::toString('fort_id', $this->fortId, "")
           . Protobuf::toString('encounter_id', $this->encounterId, 0)
           . Protobuf::toString('active_pokemon_id', $this->activePokemonId, PokemonId::MISSINGNO)
           . Protobuf::toString('lure_expires_timestamp_ms', $this->lureExpiresTimestampMs, 0);
    }

    // @@protoc_insertion_point(class_scope:POGOProtos.Map.Fort.FortLureInfo)
  }

}