<?php
// Generated by https://github.com/bramp/protoc-gen-php// Please include protocolbuffers before this file, for example:
//   require('protocolbuffers.inc.php');
//   require('POGOProtos/Enums/CameraTarget.php');

namespace POGOProtos\Enums {

  use Protobuf;
  use ProtobufEnum;
  use ProtobufIO;
  use ProtobufMessage;

  // enum POGOProtos.Enums.CameraTarget
  abstract class CameraTarget extends ProtobufEnum {
    const CAM_TARGET_ATTACKER = 0;
    const CAM_TARGET_ATTACKER_EDGE = 1;
    const CAM_TARGET_ATTACKER_GROUND = 2;
    const CAM_TARGET_DEFENDER = 3;
    const CAM_TARGET_DEFENDER_EDGE = 4;
    const CAM_TARGET_DEFENDER_GROUND = 5;
    const CAM_TARGET_ATTACKER_DEFENDER = 6;
    const CAM_TARGET_ATTACKER_DEFENDER_EDGE = 7;
    const CAM_TARGET_DEFENDER_ATTACKER = 8;
    const CAM_TARGET_DEFENDER_ATTACKER_EDGE = 9;
    const CAM_TARGET_ATTACKER_DEFENDER_MIRROR = 11;
    const CAM_TARGET_SHOULDER_ATTACKER_DEFENDER = 12;
    const CAM_TARGET_SHOULDER_ATTACKER_DEFENDER_MIRROR = 13;
    const CAM_TARGET_ATTACKER_DEFENDER_WORLD = 14;

    public static $_values = array(
      0 => "CAM_TARGET_ATTACKER",
      1 => "CAM_TARGET_ATTACKER_EDGE",
      2 => "CAM_TARGET_ATTACKER_GROUND",
      3 => "CAM_TARGET_DEFENDER",
      4 => "CAM_TARGET_DEFENDER_EDGE",
      5 => "CAM_TARGET_DEFENDER_GROUND",
      6 => "CAM_TARGET_ATTACKER_DEFENDER",
      7 => "CAM_TARGET_ATTACKER_DEFENDER_EDGE",
      8 => "CAM_TARGET_DEFENDER_ATTACKER",
      9 => "CAM_TARGET_DEFENDER_ATTACKER_EDGE",
      11 => "CAM_TARGET_ATTACKER_DEFENDER_MIRROR",
      12 => "CAM_TARGET_SHOULDER_ATTACKER_DEFENDER",
      13 => "CAM_TARGET_SHOULDER_ATTACKER_DEFENDER_MIRROR",
      14 => "CAM_TARGET_ATTACKER_DEFENDER_WORLD",
    );

    public static function isValid($value) {
      return array_key_exists($value, self::$_values);
    }

    public static function toString($value) {
      checkArgument(is_int($value), 'value must be a integer');
      if (array_key_exists($value, self::$_values))
        return self::$_values[$value];
      return 'UNKNOWN';
    }
  }

}