<?php
// Generated by https://github.com/bramp/protoc-gen-php// Please include protocolbuffers before this file, for example:
//   require('protocolbuffers.inc.php');
//   require('POGOProtos/Enums/CameraInterpolation.php');

namespace POGOProtos\Enums {

  use Protobuf;
  use ProtobufEnum;
  use ProtobufIO;
  use ProtobufMessage;

  // enum POGOProtos.Enums.CameraInterpolation
  abstract class CameraInterpolation extends ProtobufEnum {
    const CAM_INTERP_CUT = 0;
    const CAM_INTERP_LINEAR = 1;
    const CAM_INTERP_SMOOTH = 2;
    const CAM_INTERP_SMOOTH_ROT_LINEAR_MOVE = 3;
    const CAM_INTERP_DEPENDS = 4;

    public static $_values = array(
      0 => "CAM_INTERP_CUT",
      1 => "CAM_INTERP_LINEAR",
      2 => "CAM_INTERP_SMOOTH",
      3 => "CAM_INTERP_SMOOTH_ROT_LINEAR_MOVE",
      4 => "CAM_INTERP_DEPENDS",
    );

    public static function isValid($value) {
      return array_key_exists($value, self::$_values);
    }

    public static function toString($value) {
      checkArgument(is_int($value), 'value must be a integer');
      if (array_key_exists($value, self::$_values))
        return self::$_values[$value];
      return 'UNKNOWN';
    }
  }

}