<?php
// Generated by https://github.com/bramp/protoc-gen-php// Please include protocolbuffers before this file, for example:
//   require('protocolbuffers.inc.php');
//   require('POGOProtos/Enums/PokemonClass.php');

namespace POGOProtos\Enums {

  use Protobuf;
  use ProtobufEnum;
  use ProtobufIO;
  use ProtobufMessage;

  // enum POGOProtos.Enums.PokemonClass
  abstract class PokemonClass extends ProtobufEnum {
    const NORMAL = 0;
    const LEGENDARY = 1;
    const MYTHIC = 2;

    public static $_values = array(
      0 => "NORMAL",
      1 => "LEGENDARY",
      2 => "MYTHIC",
    );

    public static function isValid($value) {
      return array_key_exists($value, self::$_values);
    }

    public static function toString($value) {
      checkArgument(is_int($value), 'value must be a integer');
      if (array_key_exists($value, self::$_values))
        return self::$_values[$value];
      return 'UNKNOWN';
    }
  }

}