<?php
// Generated by https://github.com/bramp/protoc-gen-php// Please include protocolbuffers before this file, for example:
//   require('protocolbuffers.inc.php');
//   require('POGOProtos/Enums/TeamColor.php');

namespace POGOProtos\Enums {

  use Protobuf;
  use ProtobufEnum;
  use ProtobufIO;
  use ProtobufMessage;

  // enum POGOProtos.Enums.TeamColor
  abstract class TeamColor extends ProtobufEnum {
    const NEUTRAL = 0;
    const BLUE = 1;
    const RED = 2;
    const YELLOW = 3;

    public static $_values = array(
      0 => "NEUTRAL",
      1 => "BLUE",
      2 => "RED",
      3 => "YELLOW",
    );

    public static function isValid($value) {
      return array_key_exists($value, self::$_values);
    }

    public static function toString($value) {
      checkArgument(is_int($value), 'value must be a integer');
      if (array_key_exists($value, self::$_values))
        return self::$_values[$value];
      return 'UNKNOWN';
    }
  }

}