<?php
// Generated by https://github.com/bramp/protoc-gen-php// Please include protocolbuffers before this file, for example:
//   require('protocolbuffers.inc.php');
//   require('POGOProtos/Networking/Responses/DownloadRemoteConfigVersionResponse.php');

namespace POGOProtos\Networking\Responses {

  use Protobuf;
  use ProtobufEnum;
  use ProtobufIO;
  use ProtobufMessage;

  // enum POGOProtos.Networking.Responses.DownloadRemoteConfigVersionResponse.Result
  abstract class DownloadRemoteConfigVersionResponse_Result extends ProtobufEnum {
    const UNSET = 0;
    const SUCCESS = 1;

    public static $_values = array(
      0 => "UNSET",
      1 => "SUCCESS",
    );

    public static function isValid($value) {
      return array_key_exists($value, self::$_values);
    }

    public static function toString($value) {
      checkArgument(is_int($value), 'value must be a integer');
      if (array_key_exists($value, self::$_values))
        return self::$_values[$value];
      return 'UNKNOWN';
    }
  }

  // message POGOProtos.Networking.Responses.DownloadRemoteConfigVersionResponse
  final class DownloadRemoteConfigVersionResponse extends ProtobufMessage {

    private $_unknown;
    private $result = DownloadRemoteConfigVersionResponse_Result::UNSET; // optional .POGOProtos.Networking.Responses.DownloadRemoteConfigVersionResponse.Result result = 1
    private $itemTemplatesTimestampMs = 0; // optional uint64 item_templates_timestamp_ms = 2
    private $assetDigestTimestampMs = 0; // optional uint64 asset_digest_timestamp_ms = 3

    public function __construct($in = null, &$limit = PHP_INT_MAX) {
      parent::__construct($in, $limit);
    }

    public function read($fp, &$limit = PHP_INT_MAX) {
      $fp = ProtobufIO::toStream($fp, $limit);
      while(!feof($fp) && $limit > 0) {
        $tag = Protobuf::read_varint($fp, $limit);
        if ($tag === false) break;
        $wire  = $tag & 0x07;
        $field = $tag >> 3;
        switch($field) {
          case 1: // optional .POGOProtos.Networking.Responses.DownloadRemoteConfigVersionResponse.Result result = 1
            if($wire !== 0) {
              throw new \Exception("Incorrect wire format for field $field, expected: 0 got: $wire");
            }
            $tmp = Protobuf::read_varint($fp, $limit);
            if ($tmp === false) throw new \Exception('Protobuf::read_varint returned false');
            $this->result = $tmp;

            break;
          case 2: // optional uint64 item_templates_timestamp_ms = 2
            if($wire !== 0) {
              throw new \Exception("Incorrect wire format for field $field, expected: 0 got: $wire");
            }
            $tmp = Protobuf::read_varint($fp, $limit);
            if ($tmp === false) throw new \Exception('Protobuf::read_varint returned false');
            if ($tmp < Protobuf::MIN_UINT64 || $tmp > Protobuf::MAX_UINT64) throw new \Exception('uint64 out of range');$this->itemTemplatesTimestampMs = $tmp;

            break;
          case 3: // optional uint64 asset_digest_timestamp_ms = 3
            if($wire !== 0) {
              throw new \Exception("Incorrect wire format for field $field, expected: 0 got: $wire");
            }
            $tmp = Protobuf::read_varint($fp, $limit);
            if ($tmp === false) throw new \Exception('Protobuf::read_varint returned false');
            if ($tmp < Protobuf::MIN_UINT64 || $tmp > Protobuf::MAX_UINT64) throw new \Exception('uint64 out of range');$this->assetDigestTimestampMs = $tmp;

            break;
          default:
            $limit -= Protobuf::skip_field($fp, $wire);
        }
      }
    }

    public function write($fp) {
      if ($this->result !== DownloadRemoteConfigVersionResponse_Result::UNSET) {
        fwrite($fp, "\x08", 1);
        Protobuf::write_varint($fp, $this->result);
      }
      if ($this->itemTemplatesTimestampMs !== 0) {
        fwrite($fp, "\x10", 1);
        Protobuf::write_varint($fp, $this->itemTemplatesTimestampMs);
      }
      if ($this->assetDigestTimestampMs !== 0) {
        fwrite($fp, "\x18", 1);
        Protobuf::write_varint($fp, $this->assetDigestTimestampMs);
      }
    }

    public function size() {
      $size = 0;
      if ($this->result !== DownloadRemoteConfigVersionResponse_Result::UNSET) {
        $size += 1 + Protobuf::size_varint($this->result);
      }
      if ($this->itemTemplatesTimestampMs !== 0) {
        $size += 1 + Protobuf::size_varint($this->itemTemplatesTimestampMs);
      }
      if ($this->assetDigestTimestampMs !== 0) {
        $size += 1 + Protobuf::size_varint($this->assetDigestTimestampMs);
      }
      return $size;
    }

    public function clearResult() { $this->result = DownloadRemoteConfigVersionResponse_Result::UNSET; }
    public function getResult() { return $this->result;}
    public function setResult($value) { $this->result = $value; }

    public function clearItemTemplatesTimestampMs() { $this->itemTemplatesTimestampMs = 0; }
    public function getItemTemplatesTimestampMs() { return $this->itemTemplatesTimestampMs;}
    public function setItemTemplatesTimestampMs($value) { $this->itemTemplatesTimestampMs = $value; }

    public function clearAssetDigestTimestampMs() { $this->assetDigestTimestampMs = 0; }
    public function getAssetDigestTimestampMs() { return $this->assetDigestTimestampMs;}
    public function setAssetDigestTimestampMs($value) { $this->assetDigestTimestampMs = $value; }

    public function __toString() {
      return ''
           . Protobuf::toString('result', $this->result, DownloadRemoteConfigVersionResponse_Result::UNSET)
           . Protobuf::toString('item_templates_timestamp_ms', $this->itemTemplatesTimestampMs, 0)
           . Protobuf::toString('asset_digest_timestamp_ms', $this->assetDigestTimestampMs, 0);
    }

    // @@protoc_insertion_point(class_scope:POGOProtos.Networking.Responses.DownloadRemoteConfigVersionResponse)
  }

}