<?php
// Generated by https://github.com/bramp/protoc-gen-php// Please include protocolbuffers before this file, for example:
//   require('protocolbuffers.inc.php');
//   require('POGOProtos/Networking/Responses/EncounterResponse.php');

namespace POGOProtos\Networking\Responses {

  use Protobuf;
  use ProtobufEnum;
  use ProtobufIO;
  use ProtobufMessage;


  // enum POGOProtos.Networking.Responses.EncounterResponse.Background
  abstract class EncounterResponse_Background extends ProtobufEnum {
    const PARK = 0;
    const DESERT = 1;

    public static $_values = array(
      0 => "PARK",
      1 => "DESERT",
    );

    public static function isValid($value) {
      return array_key_exists($value, self::$_values);
    }

    public static function toString($value) {
      checkArgument(is_int($value), 'value must be a integer');
      if (array_key_exists($value, self::$_values))
        return self::$_values[$value];
      return 'UNKNOWN';
    }
  }

  // enum POGOProtos.Networking.Responses.EncounterResponse.Status
  abstract class EncounterResponse_Status extends ProtobufEnum {
    const ENCOUNTER_ERROR = 0;
    const ENCOUNTER_SUCCESS = 1;
    const ENCOUNTER_NOT_FOUND = 2;
    const ENCOUNTER_CLOSED = 3;
    const ENCOUNTER_POKEMON_FLED = 4;
    const ENCOUNTER_NOT_IN_RANGE = 5;
    const ENCOUNTER_ALREADY_HAPPENED = 6;
    const POKEMON_INVENTORY_FULL = 7;

    public static $_values = array(
      0 => "ENCOUNTER_ERROR",
      1 => "ENCOUNTER_SUCCESS",
      2 => "ENCOUNTER_NOT_FOUND",
      3 => "ENCOUNTER_CLOSED",
      4 => "ENCOUNTER_POKEMON_FLED",
      5 => "ENCOUNTER_NOT_IN_RANGE",
      6 => "ENCOUNTER_ALREADY_HAPPENED",
      7 => "POKEMON_INVENTORY_FULL",
    );

    public static function isValid($value) {
      return array_key_exists($value, self::$_values);
    }

    public static function toString($value) {
      checkArgument(is_int($value), 'value must be a integer');
      if (array_key_exists($value, self::$_values))
        return self::$_values[$value];
      return 'UNKNOWN';
    }
  }

  // message POGOProtos.Networking.Responses.EncounterResponse
  final class EncounterResponse extends ProtobufMessage {

    private $_unknown;
    private $wildPokemon = null; // optional .POGOProtos.Map.Pokemon.WildPokemon wild_pokemon = 1
    private $background = EncounterResponse_Background::PARK; // optional .POGOProtos.Networking.Responses.EncounterResponse.Background background = 2
    private $status = EncounterResponse_Status::ENCOUNTER_ERROR; // optional .POGOProtos.Networking.Responses.EncounterResponse.Status status = 3
    private $captureProbability = null; // optional .POGOProtos.Data.Capture.CaptureProbability capture_probability = 4

    public function __construct($in = null, &$limit = PHP_INT_MAX) {
      parent::__construct($in, $limit);
    }

    public function read($fp, &$limit = PHP_INT_MAX) {
      $fp = ProtobufIO::toStream($fp, $limit);
      while(!feof($fp) && $limit > 0) {
        $tag = Protobuf::read_varint($fp, $limit);
        if ($tag === false) break;
        $wire  = $tag & 0x07;
        $field = $tag >> 3;
        switch($field) {
          case 1: // optional .POGOProtos.Map.Pokemon.WildPokemon wild_pokemon = 1
            if($wire !== 2) {
              throw new \Exception("Incorrect wire format for field $field, expected: 2 got: $wire");
            }
            $len = Protobuf::read_varint($fp, $limit);
            if ($len === false) throw new \Exception('Protobuf::read_varint returned false');
            $limit -= $len;
            $this->wildPokemon = new \POGOProtos\Map\Pokemon\WildPokemon($fp, $len);
            if ($len !== 0) throw new \Exception('new \POGOProtos\Map\Pokemon\WildPokemon did not read the full length');

            break;
          case 2: // optional .POGOProtos.Networking.Responses.EncounterResponse.Background background = 2
            if($wire !== 0) {
              throw new \Exception("Incorrect wire format for field $field, expected: 0 got: $wire");
            }
            $tmp = Protobuf::read_varint($fp, $limit);
            if ($tmp === false) throw new \Exception('Protobuf::read_varint returned false');
            $this->background = $tmp;

            break;
          case 3: // optional .POGOProtos.Networking.Responses.EncounterResponse.Status status = 3
            if($wire !== 0) {
              throw new \Exception("Incorrect wire format for field $field, expected: 0 got: $wire");
            }
            $tmp = Protobuf::read_varint($fp, $limit);
            if ($tmp === false) throw new \Exception('Protobuf::read_varint returned false');
            $this->status = $tmp;

            break;
          case 4: // optional .POGOProtos.Data.Capture.CaptureProbability capture_probability = 4
            if($wire !== 2) {
              throw new \Exception("Incorrect wire format for field $field, expected: 2 got: $wire");
            }
            $len = Protobuf::read_varint($fp, $limit);
            if ($len === false) throw new \Exception('Protobuf::read_varint returned false');
            $limit -= $len;
            $this->captureProbability = new \POGOProtos\Data\Capture\CaptureProbability($fp, $len);
            if ($len !== 0) throw new \Exception('new \POGOProtos\Data\Capture\CaptureProbability did not read the full length');

            break;
          default:
            $limit -= Protobuf::skip_field($fp, $wire);
        }
      }
    }

    public function write($fp) {
      if ($this->wildPokemon !== null) {
        fwrite($fp, "\x0a", 1);
        Protobuf::write_varint($fp, $this->wildPokemon->size());
        $this->wildPokemon->write($fp);
      }
      if ($this->background !== EncounterResponse_Background::PARK) {
        fwrite($fp, "\x10", 1);
        Protobuf::write_varint($fp, $this->background);
      }
      if ($this->status !== EncounterResponse_Status::ENCOUNTER_ERROR) {
        fwrite($fp, "\x18", 1);
        Protobuf::write_varint($fp, $this->status);
      }
      if ($this->captureProbability !== null) {
        fwrite($fp, "\"", 1);
        Protobuf::write_varint($fp, $this->captureProbability->size());
        $this->captureProbability->write($fp);
      }
    }

    public function size() {
      $size = 0;
      if ($this->wildPokemon !== null) {
        $l = $this->wildPokemon->size();
        $size += 1 + Protobuf::size_varint($l) + $l;
      }
      if ($this->background !== EncounterResponse_Background::PARK) {
        $size += 1 + Protobuf::size_varint($this->background);
      }
      if ($this->status !== EncounterResponse_Status::ENCOUNTER_ERROR) {
        $size += 1 + Protobuf::size_varint($this->status);
      }
      if ($this->captureProbability !== null) {
        $l = $this->captureProbability->size();
        $size += 1 + Protobuf::size_varint($l) + $l;
      }
      return $size;
    }

    public function clearWildPokemon() { $this->wildPokemon = null; }
    public function getWildPokemon() { return $this->wildPokemon;}
    public function setWildPokemon(\POGOProtos\Map\Pokemon\WildPokemon $value) { $this->wildPokemon = $value; }

    public function clearBackground() { $this->background = EncounterResponse_Background::PARK; }
    public function getBackground() { return $this->background;}
    public function setBackground($value) { $this->background = $value; }

    public function clearStatus() { $this->status = EncounterResponse_Status::ENCOUNTER_ERROR; }
    public function getStatus() { return $this->status;}
    public function setStatus($value) { $this->status = $value; }

    public function clearCaptureProbability() { $this->captureProbability = null; }
    public function getCaptureProbability() { return $this->captureProbability;}
    public function setCaptureProbability(\POGOProtos\Data\Capture\CaptureProbability $value) { $this->captureProbability = $value; }

    public function __toString() {
      return ''
           . Protobuf::toString('wild_pokemon', $this->wildPokemon, null)
           . Protobuf::toString('background', $this->background, EncounterResponse_Background::PARK)
           . Protobuf::toString('status', $this->status, EncounterResponse_Status::ENCOUNTER_ERROR)
           . Protobuf::toString('capture_probability', $this->captureProbability, null);
    }

    // @@protoc_insertion_point(class_scope:POGOProtos.Networking.Responses.EncounterResponse)
  }

}