<?php
// Generated by https://github.com/bramp/protoc-gen-php// Please include protocolbuffers before this file, for example:
//   require('protocolbuffers.inc.php');
//   require('POGOProtos/Networking/Responses/EquipBadgeResponse.php');

namespace POGOProtos\Networking\Responses {

  use Protobuf;
  use ProtobufEnum;
  use ProtobufIO;
  use ProtobufMessage;


  // enum POGOProtos.Networking.Responses.EquipBadgeResponse.Result
  abstract class EquipBadgeResponse_Result extends ProtobufEnum {
    const UNSET = 0;
    const SUCCESS = 1;
    const COOLDOWN_ACTIVE = 2;
    const NOT_QUALIFIED = 3;

    public static $_values = array(
      0 => "UNSET",
      1 => "SUCCESS",
      2 => "COOLDOWN_ACTIVE",
      3 => "NOT_QUALIFIED",
    );

    public static function isValid($value) {
      return array_key_exists($value, self::$_values);
    }

    public static function toString($value) {
      checkArgument(is_int($value), 'value must be a integer');
      if (array_key_exists($value, self::$_values))
        return self::$_values[$value];
      return 'UNKNOWN';
    }
  }

  // message POGOProtos.Networking.Responses.EquipBadgeResponse
  final class EquipBadgeResponse extends ProtobufMessage {

    private $_unknown;
    private $result = EquipBadgeResponse_Result::UNSET; // optional .POGOProtos.Networking.Responses.EquipBadgeResponse.Result result = 1
    private $equipped = null; // optional .POGOProtos.Data.Player.EquippedBadge equipped = 2

    public function __construct($in = null, &$limit = PHP_INT_MAX) {
      parent::__construct($in, $limit);
    }

    public function read($fp, &$limit = PHP_INT_MAX) {
      $fp = ProtobufIO::toStream($fp, $limit);
      while(!feof($fp) && $limit > 0) {
        $tag = Protobuf::read_varint($fp, $limit);
        if ($tag === false) break;
        $wire  = $tag & 0x07;
        $field = $tag >> 3;
        switch($field) {
          case 1: // optional .POGOProtos.Networking.Responses.EquipBadgeResponse.Result result = 1
            if($wire !== 0) {
              throw new \Exception("Incorrect wire format for field $field, expected: 0 got: $wire");
            }
            $tmp = Protobuf::read_varint($fp, $limit);
            if ($tmp === false) throw new \Exception('Protobuf::read_varint returned false');
            $this->result = $tmp;

            break;
          case 2: // optional .POGOProtos.Data.Player.EquippedBadge equipped = 2
            if($wire !== 2) {
              throw new \Exception("Incorrect wire format for field $field, expected: 2 got: $wire");
            }
            $len = Protobuf::read_varint($fp, $limit);
            if ($len === false) throw new \Exception('Protobuf::read_varint returned false');
            $limit -= $len;
            $this->equipped = new \POGOProtos\Data\Player\EquippedBadge($fp, $len);
            if ($len !== 0) throw new \Exception('new \POGOProtos\Data\Player\EquippedBadge did not read the full length');

            break;
          default:
            $limit -= Protobuf::skip_field($fp, $wire);
        }
      }
    }

    public function write($fp) {
      if ($this->result !== EquipBadgeResponse_Result::UNSET) {
        fwrite($fp, "\x08", 1);
        Protobuf::write_varint($fp, $this->result);
      }
      if ($this->equipped !== null) {
        fwrite($fp, "\x12", 1);
        Protobuf::write_varint($fp, $this->equipped->size());
        $this->equipped->write($fp);
      }
    }

    public function size() {
      $size = 0;
      if ($this->result !== EquipBadgeResponse_Result::UNSET) {
        $size += 1 + Protobuf::size_varint($this->result);
      }
      if ($this->equipped !== null) {
        $l = $this->equipped->size();
        $size += 1 + Protobuf::size_varint($l) + $l;
      }
      return $size;
    }

    public function clearResult() { $this->result = EquipBadgeResponse_Result::UNSET; }
    public function getResult() { return $this->result;}
    public function setResult($value) { $this->result = $value; }

    public function clearEquipped() { $this->equipped = null; }
    public function getEquipped() { return $this->equipped;}
    public function setEquipped(\POGOProtos\Data\Player\EquippedBadge $value) { $this->equipped = $value; }

    public function __toString() {
      return ''
           . Protobuf::toString('result', $this->result, EquipBadgeResponse_Result::UNSET)
           . Protobuf::toString('equipped', $this->equipped, null);
    }

    // @@protoc_insertion_point(class_scope:POGOProtos.Networking.Responses.EquipBadgeResponse)
  }

}