<?php
// Generated by https://github.com/bramp/protoc-gen-php// Please include protocolbuffers before this file, for example:
//   require('protocolbuffers.inc.php');
//   require('POGOProtos/Networking/Responses/EvolvePokemonResponse.php');

namespace POGOProtos\Networking\Responses {

  use Protobuf;
  use ProtobufEnum;
  use ProtobufIO;
  use ProtobufMessage;


  // enum POGOProtos.Networking.Responses.EvolvePokemonResponse.Result
  abstract class EvolvePokemonResponse_Result extends ProtobufEnum {
    const UNSET = 0;
    const SUCCESS = 1;
    const FAILED_POKEMON_MISSING = 2;
    const FAILED_INSUFFICIENT_RESOURCES = 3;
    const FAILED_POKEMON_CANNOT_EVOLVE = 4;
    const FAILED_POKEMON_IS_DEPLOYED = 5;

    public static $_values = array(
      0 => "UNSET",
      1 => "SUCCESS",
      2 => "FAILED_POKEMON_MISSING",
      3 => "FAILED_INSUFFICIENT_RESOURCES",
      4 => "FAILED_POKEMON_CANNOT_EVOLVE",
      5 => "FAILED_POKEMON_IS_DEPLOYED",
    );

    public static function isValid($value) {
      return array_key_exists($value, self::$_values);
    }

    public static function toString($value) {
      checkArgument(is_int($value), 'value must be a integer');
      if (array_key_exists($value, self::$_values))
        return self::$_values[$value];
      return 'UNKNOWN';
    }
  }

  // message POGOProtos.Networking.Responses.EvolvePokemonResponse
  final class EvolvePokemonResponse extends ProtobufMessage {

    private $_unknown;
    private $result = EvolvePokemonResponse_Result::UNSET; // optional .POGOProtos.Networking.Responses.EvolvePokemonResponse.Result result = 1
    private $evolvedPokemonData = null; // optional .POGOProtos.Data.PokemonData evolved_pokemon_data = 2
    private $experienceAwarded = 0; // optional int32 experience_awarded = 3
    private $candyAwarded = 0; // optional int32 candy_awarded = 4

    public function __construct($in = null, &$limit = PHP_INT_MAX) {
      parent::__construct($in, $limit);
    }

    public function read($fp, &$limit = PHP_INT_MAX) {
      $fp = ProtobufIO::toStream($fp, $limit);
      while(!feof($fp) && $limit > 0) {
        $tag = Protobuf::read_varint($fp, $limit);
        if ($tag === false) break;
        $wire  = $tag & 0x07;
        $field = $tag >> 3;
        switch($field) {
          case 1: // optional .POGOProtos.Networking.Responses.EvolvePokemonResponse.Result result = 1
            if($wire !== 0) {
              throw new \Exception("Incorrect wire format for field $field, expected: 0 got: $wire");
            }
            $tmp = Protobuf::read_varint($fp, $limit);
            if ($tmp === false) throw new \Exception('Protobuf::read_varint returned false');
            $this->result = $tmp;

            break;
          case 2: // optional .POGOProtos.Data.PokemonData evolved_pokemon_data = 2
            if($wire !== 2) {
              throw new \Exception("Incorrect wire format for field $field, expected: 2 got: $wire");
            }
            $len = Protobuf::read_varint($fp, $limit);
            if ($len === false) throw new \Exception('Protobuf::read_varint returned false');
            $limit -= $len;
            $this->evolvedPokemonData = new \POGOProtos\Data\PokemonData($fp, $len);
            if ($len !== 0) throw new \Exception('new \POGOProtos\Data\PokemonData did not read the full length');

            break;
          case 3: // optional int32 experience_awarded = 3
            if($wire !== 0) {
              throw new \Exception("Incorrect wire format for field $field, expected: 0 got: $wire");
            }
            $tmp = Protobuf::read_signed_varint($fp, $limit);
            if ($tmp === false) throw new \Exception('Protobuf::read_varint returned false');
            if ($tmp < Protobuf::MIN_INT32 || $tmp > Protobuf::MAX_INT32) throw new \Exception('int32 out of range');$this->experienceAwarded = $tmp;

            break;
          case 4: // optional int32 candy_awarded = 4
            if($wire !== 0) {
              throw new \Exception("Incorrect wire format for field $field, expected: 0 got: $wire");
            }
            $tmp = Protobuf::read_signed_varint($fp, $limit);
            if ($tmp === false) throw new \Exception('Protobuf::read_varint returned false');
            if ($tmp < Protobuf::MIN_INT32 || $tmp > Protobuf::MAX_INT32) throw new \Exception('int32 out of range');$this->candyAwarded = $tmp;

            break;
          default:
            $limit -= Protobuf::skip_field($fp, $wire);
        }
      }
    }

    public function write($fp) {
      if ($this->result !== EvolvePokemonResponse_Result::UNSET) {
        fwrite($fp, "\x08", 1);
        Protobuf::write_varint($fp, $this->result);
      }
      if ($this->evolvedPokemonData !== null) {
        fwrite($fp, "\x12", 1);
        Protobuf::write_varint($fp, $this->evolvedPokemonData->size());
        $this->evolvedPokemonData->write($fp);
      }
      if ($this->experienceAwarded !== 0) {
        fwrite($fp, "\x18", 1);
        Protobuf::write_varint($fp, $this->experienceAwarded);
      }
      if ($this->candyAwarded !== 0) {
        fwrite($fp, " ", 1);
        Protobuf::write_varint($fp, $this->candyAwarded);
      }
    }

    public function size() {
      $size = 0;
      if ($this->result !== EvolvePokemonResponse_Result::UNSET) {
        $size += 1 + Protobuf::size_varint($this->result);
      }
      if ($this->evolvedPokemonData !== null) {
        $l = $this->evolvedPokemonData->size();
        $size += 1 + Protobuf::size_varint($l) + $l;
      }
      if ($this->experienceAwarded !== 0) {
        $size += 1 + Protobuf::size_varint($this->experienceAwarded);
      }
      if ($this->candyAwarded !== 0) {
        $size += 1 + Protobuf::size_varint($this->candyAwarded);
      }
      return $size;
    }

    public function clearResult() { $this->result = EvolvePokemonResponse_Result::UNSET; }
    public function getResult() { return $this->result;}
    public function setResult($value) { $this->result = $value; }

    public function clearEvolvedPokemonData() { $this->evolvedPokemonData = null; }
    public function getEvolvedPokemonData() { return $this->evolvedPokemonData;}
    public function setEvolvedPokemonData(\POGOProtos\Data\PokemonData $value) { $this->evolvedPokemonData = $value; }

    public function clearExperienceAwarded() { $this->experienceAwarded = 0; }
    public function getExperienceAwarded() { return $this->experienceAwarded;}
    public function setExperienceAwarded($value) { $this->experienceAwarded = $value; }

    public function clearCandyAwarded() { $this->candyAwarded = 0; }
    public function getCandyAwarded() { return $this->candyAwarded;}
    public function setCandyAwarded($value) { $this->candyAwarded = $value; }

    public function __toString() {
      return ''
           . Protobuf::toString('result', $this->result, EvolvePokemonResponse_Result::UNSET)
           . Protobuf::toString('evolved_pokemon_data', $this->evolvedPokemonData, null)
           . Protobuf::toString('experience_awarded', $this->experienceAwarded, 0)
           . Protobuf::toString('candy_awarded', $this->candyAwarded, 0);
    }

    // @@protoc_insertion_point(class_scope:POGOProtos.Networking.Responses.EvolvePokemonResponse)
  }

}