<?php
// Generated by https://github.com/bramp/protoc-gen-php// Please include protocolbuffers before this file, for example:
//   require('protocolbuffers.inc.php');
//   require('POGOProtos/Networking/Responses/IncenseEncounterResponse.php');

namespace POGOProtos\Networking\Responses {

  use Protobuf;
  use ProtobufEnum;
  use ProtobufIO;
  use ProtobufMessage;


  // enum POGOProtos.Networking.Responses.IncenseEncounterResponse.Result
  abstract class IncenseEncounterResponse_Result extends ProtobufEnum {
    const INCENSE_ENCOUNTER_UNKNOWN = 0;
    const INCENSE_ENCOUNTER_SUCCESS = 1;
    const INCENSE_ENCOUNTER_NOT_AVAILABLE = 2;
    const POKEMON_INVENTORY_FULL = 3;

    public static $_values = array(
      0 => "INCENSE_ENCOUNTER_UNKNOWN",
      1 => "INCENSE_ENCOUNTER_SUCCESS",
      2 => "INCENSE_ENCOUNTER_NOT_AVAILABLE",
      3 => "POKEMON_INVENTORY_FULL",
    );

    public static function isValid($value) {
      return array_key_exists($value, self::$_values);
    }

    public static function toString($value) {
      checkArgument(is_int($value), 'value must be a integer');
      if (array_key_exists($value, self::$_values))
        return self::$_values[$value];
      return 'UNKNOWN';
    }
  }

  // message POGOProtos.Networking.Responses.IncenseEncounterResponse
  final class IncenseEncounterResponse extends ProtobufMessage {

    private $_unknown;
    private $result = IncenseEncounterResponse_Result::INCENSE_ENCOUNTER_UNKNOWN; // optional .POGOProtos.Networking.Responses.IncenseEncounterResponse.Result result = 1
    private $pokemonData = null; // optional .POGOProtos.Data.PokemonData pokemon_data = 2
    private $captureProbability = null; // optional .POGOProtos.Data.Capture.CaptureProbability capture_probability = 3

    public function __construct($in = null, &$limit = PHP_INT_MAX) {
      parent::__construct($in, $limit);
    }

    public function read($fp, &$limit = PHP_INT_MAX) {
      $fp = ProtobufIO::toStream($fp, $limit);
      while(!feof($fp) && $limit > 0) {
        $tag = Protobuf::read_varint($fp, $limit);
        if ($tag === false) break;
        $wire  = $tag & 0x07;
        $field = $tag >> 3;
        switch($field) {
          case 1: // optional .POGOProtos.Networking.Responses.IncenseEncounterResponse.Result result = 1
            if($wire !== 0) {
              throw new \Exception("Incorrect wire format for field $field, expected: 0 got: $wire");
            }
            $tmp = Protobuf::read_varint($fp, $limit);
            if ($tmp === false) throw new \Exception('Protobuf::read_varint returned false');
            $this->result = $tmp;

            break;
          case 2: // optional .POGOProtos.Data.PokemonData pokemon_data = 2
            if($wire !== 2) {
              throw new \Exception("Incorrect wire format for field $field, expected: 2 got: $wire");
            }
            $len = Protobuf::read_varint($fp, $limit);
            if ($len === false) throw new \Exception('Protobuf::read_varint returned false');
            $limit -= $len;
            $this->pokemonData = new \POGOProtos\Data\PokemonData($fp, $len);
            if ($len !== 0) throw new \Exception('new \POGOProtos\Data\PokemonData did not read the full length');

            break;
          case 3: // optional .POGOProtos.Data.Capture.CaptureProbability capture_probability = 3
            if($wire !== 2) {
              throw new \Exception("Incorrect wire format for field $field, expected: 2 got: $wire");
            }
            $len = Protobuf::read_varint($fp, $limit);
            if ($len === false) throw new \Exception('Protobuf::read_varint returned false');
            $limit -= $len;
            $this->captureProbability = new \POGOProtos\Data\Capture\CaptureProbability($fp, $len);
            if ($len !== 0) throw new \Exception('new \POGOProtos\Data\Capture\CaptureProbability did not read the full length');

            break;
          default:
            $limit -= Protobuf::skip_field($fp, $wire);
        }
      }
    }

    public function write($fp) {
      if ($this->result !== IncenseEncounterResponse_Result::INCENSE_ENCOUNTER_UNKNOWN) {
        fwrite($fp, "\x08", 1);
        Protobuf::write_varint($fp, $this->result);
      }
      if ($this->pokemonData !== null) {
        fwrite($fp, "\x12", 1);
        Protobuf::write_varint($fp, $this->pokemonData->size());
        $this->pokemonData->write($fp);
      }
      if ($this->captureProbability !== null) {
        fwrite($fp, "\x1a", 1);
        Protobuf::write_varint($fp, $this->captureProbability->size());
        $this->captureProbability->write($fp);
      }
    }

    public function size() {
      $size = 0;
      if ($this->result !== IncenseEncounterResponse_Result::INCENSE_ENCOUNTER_UNKNOWN) {
        $size += 1 + Protobuf::size_varint($this->result);
      }
      if ($this->pokemonData !== null) {
        $l = $this->pokemonData->size();
        $size += 1 + Protobuf::size_varint($l) + $l;
      }
      if ($this->captureProbability !== null) {
        $l = $this->captureProbability->size();
        $size += 1 + Protobuf::size_varint($l) + $l;
      }
      return $size;
    }

    public function clearResult() { $this->result = IncenseEncounterResponse_Result::INCENSE_ENCOUNTER_UNKNOWN; }
    public function getResult() { return $this->result;}
    public function setResult($value) { $this->result = $value; }

    public function clearPokemonData() { $this->pokemonData = null; }
    public function getPokemonData() { return $this->pokemonData;}
    public function setPokemonData(\POGOProtos\Data\PokemonData $value) { $this->pokemonData = $value; }

    public function clearCaptureProbability() { $this->captureProbability = null; }
    public function getCaptureProbability() { return $this->captureProbability;}
    public function setCaptureProbability(\POGOProtos\Data\Capture\CaptureProbability $value) { $this->captureProbability = $value; }

    public function __toString() {
      return ''
           . Protobuf::toString('result', $this->result, IncenseEncounterResponse_Result::INCENSE_ENCOUNTER_UNKNOWN)
           . Protobuf::toString('pokemon_data', $this->pokemonData, null)
           . Protobuf::toString('capture_probability', $this->captureProbability, null);
    }

    // @@protoc_insertion_point(class_scope:POGOProtos.Networking.Responses.IncenseEncounterResponse)
  }

}