<?php
// Generated by https://github.com/bramp/protoc-gen-php// Please include protocolbuffers before this file, for example:
//   require('protocolbuffers.inc.php');
//   require('POGOProtos/Networking/Responses/LevelUpRewardsResponse.php');

namespace POGOProtos\Networking\Responses {

  use Protobuf;
  use ProtobufEnum;
  use ProtobufIO;
  use ProtobufMessage;


  // enum POGOProtos.Networking.Responses.LevelUpRewardsResponse.Result
  abstract class LevelUpRewardsResponse_Result extends ProtobufEnum {
    const UNSET = 0;
    const SUCCESS = 1;
    const AWARDED_ALREADY = 2;

    public static $_values = array(
      0 => "UNSET",
      1 => "SUCCESS",
      2 => "AWARDED_ALREADY",
    );

    public static function isValid($value) {
      return array_key_exists($value, self::$_values);
    }

    public static function toString($value) {
      checkArgument(is_int($value), 'value must be a integer');
      if (array_key_exists($value, self::$_values))
        return self::$_values[$value];
      return 'UNKNOWN';
    }
  }

  // message POGOProtos.Networking.Responses.LevelUpRewardsResponse
  final class LevelUpRewardsResponse extends ProtobufMessage {

    private $_unknown;
    private $result = LevelUpRewardsResponse_Result::UNSET; // optional .POGOProtos.Networking.Responses.LevelUpRewardsResponse.Result result = 1
    private $itemsAwarded = array(); // repeated .POGOProtos.Inventory.Item.ItemAward items_awarded = 2
    private $itemsUnlocked = array(); // repeated .POGOProtos.Inventory.Item.ItemId items_unlocked = 4

    public function __construct($in = null, &$limit = PHP_INT_MAX) {
      parent::__construct($in, $limit);
    }

    public function read($fp, &$limit = PHP_INT_MAX) {
      $fp = ProtobufIO::toStream($fp, $limit);
      while(!feof($fp) && $limit > 0) {
        $tag = Protobuf::read_varint($fp, $limit);
        if ($tag === false) break;
        $wire  = $tag & 0x07;
        $field = $tag >> 3;
        switch($field) {
          case 1: // optional .POGOProtos.Networking.Responses.LevelUpRewardsResponse.Result result = 1
            if($wire !== 0) {
              throw new \Exception("Incorrect wire format for field $field, expected: 0 got: $wire");
            }
            $tmp = Protobuf::read_varint($fp, $limit);
            if ($tmp === false) throw new \Exception('Protobuf::read_varint returned false');
            $this->result = $tmp;

            break;
          case 2: // repeated .POGOProtos.Inventory.Item.ItemAward items_awarded = 2
            if($wire !== 2) {
              throw new \Exception("Incorrect wire format for field $field, expected: 2 got: $wire");
            }
            $len = Protobuf::read_varint($fp, $limit);
            if ($len === false) throw new \Exception('Protobuf::read_varint returned false');
            $limit -= $len;
            $this->itemsAwarded[] = new \POGOProtos\Inventory\Item\ItemAward($fp, $len);
            if ($len !== 0) throw new \Exception('new \POGOProtos\Inventory\Item\ItemAward did not read the full length');

            break;
          case 4: // repeated .POGOProtos.Inventory.Item.ItemId items_unlocked = 4
            if($wire !== 2 && $wire !== 0) {
              throw new \Exception("Incorrect wire format for field $field, expected: 2 or 0 got: $wire");
            }
            if ($wire === 0) {
              $tmp = Protobuf::read_varint($fp, $limit);
              if ($tmp === false) throw new \Exception('Protobuf::read_varint returned false');
              $this->itemsUnlocked[] = $tmp;
            } elseif ($wire === 2) {
              $len = Protobuf::read_varint($fp, $limit);
              while ($len > 0) {
                $tmp = Protobuf::read_varint($fp, $len);
                if ($tmp === false) throw new \Exception('Protobuf::read_varint returned false');
                $this->itemsUnlocked[] = $tmp;
              }
            }

            break;
          default:
            $limit -= Protobuf::skip_field($fp, $wire);
        }
      }
    }

    public function write($fp) {
      if ($this->result !== LevelUpRewardsResponse_Result::UNSET) {
        fwrite($fp, "\x08", 1);
        Protobuf::write_varint($fp, $this->result);
      }
      foreach($this->itemsAwarded as $v) {
        fwrite($fp, "\x12", 1);
        Protobuf::write_varint($fp, $v->size());
        $v->write($fp);
      }
      foreach($this->itemsUnlocked as $v) {
        fwrite($fp, " ", 1);
        Protobuf::write_varint($fp, $v);
      }
    }

    public function size() {
      $size = 0;
      if ($this->result !== LevelUpRewardsResponse_Result::UNSET) {
        $size += 1 + Protobuf::size_varint($this->result);
      }
      foreach($this->itemsAwarded as $v) {
        $l = $v->size();
        $size += 1 + Protobuf::size_varint($l) + $l;
      }
      foreach($this->itemsUnlocked as $v) {
        $l = strlen($v);
        $size += 1 + Protobuf::size_varint($l) + $l;
      }
      return $size;
    }

    public function clearResult() { $this->result = LevelUpRewardsResponse_Result::UNSET; }
    public function getResult() { return $this->result;}
    public function setResult($value) { $this->result = $value; }

    public function clearItemsAwarded() { $this->itemsAwarded = array(); }
    public function getItemsAwardedCount() { return count($this->itemsAwarded); }
    public function getItemsAwarded($index) { return $this->itemsAwarded[$index]; }
    public function getItemsAwardedArray() { return $this->itemsAwarded; }
    public function setItemsAwarded($index, array $value) {$this->itemsAwarded[$index] = $value; }
    public function addItemsAwarded(array $value) { $this->itemsAwarded[] = $value; }
    public function addAllItemsAwarded(array $values) { foreach($values as $value) {$this->itemsAwarded[] = $value; }}

    public function clearItemsUnlocked() { $this->itemsUnlocked = array(); }
    public function getItemsUnlockedCount() { return count($this->itemsUnlocked); }
    public function getItemsUnlocked($index) { return $this->itemsUnlocked[$index]; }
    public function getItemsUnlockedArray() { return $this->itemsUnlocked; }
    public function setItemsUnlocked($index, array $value) {$this->itemsUnlocked[$index] = $value; }
    public function addItemsUnlocked(array $value) { $this->itemsUnlocked[] = $value; }
    public function addAllItemsUnlocked(array $values) { foreach($values as $value) {$this->itemsUnlocked[] = $value; }}

    public function __toString() {
      return ''
           . Protobuf::toString('result', $this->result, LevelUpRewardsResponse_Result::UNSET)
           . Protobuf::toString('items_awarded', $this->itemsAwarded, null)
           . Protobuf::toString('items_unlocked', $this->itemsUnlocked, ItemId::ITEM_UNKNOWN);
    }

    // @@protoc_insertion_point(class_scope:POGOProtos.Networking.Responses.LevelUpRewardsResponse)
  }

}