<?php
// Generated by https://github.com/bramp/protoc-gen-php// Please include protocolbuffers before this file, for example:
//   require('protocolbuffers.inc.php');
//   require('POGOProtos/Data/Battle/BattleState.php');

namespace POGOProtos\Data\Battle {

  use Protobuf;
  use ProtobufEnum;
  use ProtobufIO;
  use ProtobufMessage;

  // enum POGOProtos.Data.Battle.BattleState
  abstract class BattleState extends ProtobufEnum {
    const STATE_UNSET = 0;
    const ACTIVE = 1;
    const VICTORY = 2;
    const DEFEATED = 3;
    const TIMED_OUT = 4;

    public static $_values = array(
      0 => "STATE_UNSET",
      1 => "ACTIVE",
      2 => "VICTORY",
      3 => "DEFEATED",
      4 => "TIMED_OUT",
    );

    public static function isValid($value) {
      return array_key_exists($value, self::$_values);
    }

    public static function toString($value) {
      checkArgument(is_int($value), 'value must be a integer');
      if (array_key_exists($value, self::$_values))
        return self::$_values[$value];
      return 'UNKNOWN';
    }
  }

}